// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: mq.proto

package mq_grpc_api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Queue         string                 `protobuf:"bytes,1,opt,name=queue,proto3" json:"queue,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutRequest) Reset() {
	*x = PutRequest{}
	mi := &file_mq_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutRequest) ProtoMessage() {}

func (x *PutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mq_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutRequest.ProtoReflect.Descriptor instead.
func (*PutRequest) Descriptor() ([]byte, []int) {
	return file_mq_proto_rawDescGZIP(), []int{0}
}

func (x *PutRequest) GetQueue() string {
	if x != nil {
		return x.Queue
	}
	return ""
}

func (x *PutRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutResponse) Reset() {
	*x = PutResponse{}
	mi := &file_mq_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutResponse) ProtoMessage() {}

func (x *PutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mq_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutResponse.ProtoReflect.Descriptor instead.
func (*PutResponse) Descriptor() ([]byte, []int) {
	return file_mq_proto_rawDescGZIP(), []int{1}
}

func (x *PutResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PutResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Queue         string                 `protobuf:"bytes,1,opt,name=queue,proto3" json:"queue,omitempty"`
	WaitMs        int32                  `protobuf:"varint,2,opt,name=wait_ms,json=waitMs,proto3" json:"wait_ms,omitempty"`
	MaxMsgBytes   int32                  `protobuf:"varint,3,opt,name=max_msg_bytes,json=maxMsgBytes,proto3" json:"max_msg_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_mq_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mq_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_mq_proto_rawDescGZIP(), []int{2}
}

func (x *GetRequest) GetQueue() string {
	if x != nil {
		return x.Queue
	}
	return ""
}

func (x *GetRequest) GetWaitMs() int32 {
	if x != nil {
		return x.WaitMs
	}
	return 0
}

func (x *GetRequest) GetMaxMsgBytes() int32 {
	if x != nil {
		return x.MaxMsgBytes
	}
	return 0
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Empty         bool                   `protobuf:"varint,3,opt,name=empty,proto3" json:"empty,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_mq_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mq_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_mq_proto_rawDescGZIP(), []int{3}
}

func (x *GetResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetResponse) GetEmpty() bool {
	if x != nil {
		return x.Empty
	}
	return false
}

func (x *GetResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type BrowseFirstRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Queue         string                 `protobuf:"bytes,1,opt,name=queue,proto3" json:"queue,omitempty"`
	WaitMs        int32                  `protobuf:"varint,2,opt,name=wait_ms,json=waitMs,proto3" json:"wait_ms,omitempty"`
	MaxMsgBytes   int32                  `protobuf:"varint,3,opt,name=max_msg_bytes,json=maxMsgBytes,proto3" json:"max_msg_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BrowseFirstRequest) Reset() {
	*x = BrowseFirstRequest{}
	mi := &file_mq_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BrowseFirstRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrowseFirstRequest) ProtoMessage() {}

func (x *BrowseFirstRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mq_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrowseFirstRequest.ProtoReflect.Descriptor instead.
func (*BrowseFirstRequest) Descriptor() ([]byte, []int) {
	return file_mq_proto_rawDescGZIP(), []int{4}
}

func (x *BrowseFirstRequest) GetQueue() string {
	if x != nil {
		return x.Queue
	}
	return ""
}

func (x *BrowseFirstRequest) GetWaitMs() int32 {
	if x != nil {
		return x.WaitMs
	}
	return 0
}

func (x *BrowseFirstRequest) GetMaxMsgBytes() int32 {
	if x != nil {
		return x.MaxMsgBytes
	}
	return 0
}

type BrowseNextRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BrowseId      string                 `protobuf:"bytes,1,opt,name=browse_id,json=browseId,proto3" json:"browse_id,omitempty"`
	WaitMs        int32                  `protobuf:"varint,2,opt,name=wait_ms,json=waitMs,proto3" json:"wait_ms,omitempty"`
	MaxMsgBytes   int32                  `protobuf:"varint,3,opt,name=max_msg_bytes,json=maxMsgBytes,proto3" json:"max_msg_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BrowseNextRequest) Reset() {
	*x = BrowseNextRequest{}
	mi := &file_mq_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BrowseNextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrowseNextRequest) ProtoMessage() {}

func (x *BrowseNextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mq_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrowseNextRequest.ProtoReflect.Descriptor instead.
func (*BrowseNextRequest) Descriptor() ([]byte, []int) {
	return file_mq_proto_rawDescGZIP(), []int{5}
}

func (x *BrowseNextRequest) GetBrowseId() string {
	if x != nil {
		return x.BrowseId
	}
	return ""
}

func (x *BrowseNextRequest) GetWaitMs() int32 {
	if x != nil {
		return x.WaitMs
	}
	return 0
}

func (x *BrowseNextRequest) GetMaxMsgBytes() int32 {
	if x != nil {
		return x.MaxMsgBytes
	}
	return 0
}

type BrowseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Empty         bool                   `protobuf:"varint,3,opt,name=empty,proto3" json:"empty,omitempty"`
	BrowseId      string                 `protobuf:"bytes,4,opt,name=browse_id,json=browseId,proto3" json:"browse_id,omitempty"`
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BrowseResponse) Reset() {
	*x = BrowseResponse{}
	mi := &file_mq_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BrowseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrowseResponse) ProtoMessage() {}

func (x *BrowseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mq_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrowseResponse.ProtoReflect.Descriptor instead.
func (*BrowseResponse) Descriptor() ([]byte, []int) {
	return file_mq_proto_rawDescGZIP(), []int{6}
}

func (x *BrowseResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *BrowseResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *BrowseResponse) GetEmpty() bool {
	if x != nil {
		return x.Empty
	}
	return false
}

func (x *BrowseResponse) GetBrowseId() string {
	if x != nil {
		return x.BrowseId
	}
	return ""
}

func (x *BrowseResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type InquireQueueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Queue         string                 `protobuf:"bytes,1,opt,name=queue,proto3" json:"queue,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InquireQueueRequest) Reset() {
	*x = InquireQueueRequest{}
	mi := &file_mq_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InquireQueueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InquireQueueRequest) ProtoMessage() {}

func (x *InquireQueueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mq_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InquireQueueRequest.ProtoReflect.Descriptor instead.
func (*InquireQueueRequest) Descriptor() ([]byte, []int) {
	return file_mq_proto_rawDescGZIP(), []int{7}
}

func (x *InquireQueueRequest) GetQueue() string {
	if x != nil {
		return x.Queue
	}
	return ""
}

type InquireQueueResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Status          string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Queue           string                 `protobuf:"bytes,2,opt,name=queue,proto3" json:"queue,omitempty"`
	QueueDesc       string                 `protobuf:"bytes,3,opt,name=queue_desc,json=queueDesc,proto3" json:"queue_desc,omitempty"`
	QueueType       int32                  `protobuf:"varint,4,opt,name=queue_type,json=queueType,proto3" json:"queue_type,omitempty"`
	QueueUsage      int32                  `protobuf:"varint,5,opt,name=queue_usage,json=queueUsage,proto3" json:"queue_usage,omitempty"`
	DefPersistence  int32                  `protobuf:"varint,6,opt,name=def_persistence,json=defPersistence,proto3" json:"def_persistence,omitempty"`
	InhibitGet      int32                  `protobuf:"varint,7,opt,name=inhibit_get,json=inhibitGet,proto3" json:"inhibit_get,omitempty"`
	InhibitPut      int32                  `protobuf:"varint,8,opt,name=inhibit_put,json=inhibitPut,proto3" json:"inhibit_put,omitempty"`
	CurrentQDepth   int32                  `protobuf:"varint,9,opt,name=current_q_depth,json=currentQDepth,proto3" json:"current_q_depth,omitempty"`
	MaxQDepth       int32                  `protobuf:"varint,10,opt,name=max_q_depth,json=maxQDepth,proto3" json:"max_q_depth,omitempty"`
	OpenInputCount  int32                  `protobuf:"varint,11,opt,name=open_input_count,json=openInputCount,proto3" json:"open_input_count,omitempty"`
	OpenOutputCount int32                  `protobuf:"varint,12,opt,name=open_output_count,json=openOutputCount,proto3" json:"open_output_count,omitempty"`
	Error           string                 `protobuf:"bytes,13,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *InquireQueueResponse) Reset() {
	*x = InquireQueueResponse{}
	mi := &file_mq_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InquireQueueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InquireQueueResponse) ProtoMessage() {}

func (x *InquireQueueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mq_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InquireQueueResponse.ProtoReflect.Descriptor instead.
func (*InquireQueueResponse) Descriptor() ([]byte, []int) {
	return file_mq_proto_rawDescGZIP(), []int{8}
}

func (x *InquireQueueResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *InquireQueueResponse) GetQueue() string {
	if x != nil {
		return x.Queue
	}
	return ""
}

func (x *InquireQueueResponse) GetQueueDesc() string {
	if x != nil {
		return x.QueueDesc
	}
	return ""
}

func (x *InquireQueueResponse) GetQueueType() int32 {
	if x != nil {
		return x.QueueType
	}
	return 0
}

func (x *InquireQueueResponse) GetQueueUsage() int32 {
	if x != nil {
		return x.QueueUsage
	}
	return 0
}

func (x *InquireQueueResponse) GetDefPersistence() int32 {
	if x != nil {
		return x.DefPersistence
	}
	return 0
}

func (x *InquireQueueResponse) GetInhibitGet() int32 {
	if x != nil {
		return x.InhibitGet
	}
	return 0
}

func (x *InquireQueueResponse) GetInhibitPut() int32 {
	if x != nil {
		return x.InhibitPut
	}
	return 0
}

func (x *InquireQueueResponse) GetCurrentQDepth() int32 {
	if x != nil {
		return x.CurrentQDepth
	}
	return 0
}

func (x *InquireQueueResponse) GetMaxQDepth() int32 {
	if x != nil {
		return x.MaxQDepth
	}
	return 0
}

func (x *InquireQueueResponse) GetOpenInputCount() int32 {
	if x != nil {
		return x.OpenInputCount
	}
	return 0
}

func (x *InquireQueueResponse) GetOpenOutputCount() int32 {
	if x != nil {
		return x.OpenOutputCount
	}
	return 0
}

func (x *InquireQueueResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_mq_proto protoreflect.FileDescriptor

const file_mq_proto_rawDesc = "" +
	"\n" +
	"\bmq.proto\x12\x04mqpb\"<\n" +
	"\n" +
	"PutRequest\x12\x14\n" +
	"\x05queue\x18\x01 \x01(\tR\x05queue\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\";\n" +
	"\vPutResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"_\n" +
	"\n" +
	"GetRequest\x12\x14\n" +
	"\x05queue\x18\x01 \x01(\tR\x05queue\x12\x17\n" +
	"\await_ms\x18\x02 \x01(\x05R\x06waitMs\x12\"\n" +
	"\rmax_msg_bytes\x18\x03 \x01(\x05R\vmaxMsgBytes\"k\n" +
	"\vGetResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x14\n" +
	"\x05empty\x18\x03 \x01(\bR\x05empty\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"g\n" +
	"\x12BrowseFirstRequest\x12\x14\n" +
	"\x05queue\x18\x01 \x01(\tR\x05queue\x12\x17\n" +
	"\await_ms\x18\x02 \x01(\x05R\x06waitMs\x12\"\n" +
	"\rmax_msg_bytes\x18\x03 \x01(\x05R\vmaxMsgBytes\"m\n" +
	"\x11BrowseNextRequest\x12\x1b\n" +
	"\tbrowse_id\x18\x01 \x01(\tR\bbrowseId\x12\x17\n" +
	"\await_ms\x18\x02 \x01(\x05R\x06waitMs\x12\"\n" +
	"\rmax_msg_bytes\x18\x03 \x01(\x05R\vmaxMsgBytes\"\x8b\x01\n" +
	"\x0eBrowseResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x14\n" +
	"\x05empty\x18\x03 \x01(\bR\x05empty\x12\x1b\n" +
	"\tbrowse_id\x18\x04 \x01(\tR\bbrowseId\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\"+\n" +
	"\x13InquireQueueRequest\x12\x14\n" +
	"\x05queue\x18\x01 \x01(\tR\x05queue\"\xc2\x03\n" +
	"\x14InquireQueueResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x14\n" +
	"\x05queue\x18\x02 \x01(\tR\x05queue\x12\x1d\n" +
	"\n" +
	"queue_desc\x18\x03 \x01(\tR\tqueueDesc\x12\x1d\n" +
	"\n" +
	"queue_type\x18\x04 \x01(\x05R\tqueueType\x12\x1f\n" +
	"\vqueue_usage\x18\x05 \x01(\x05R\n" +
	"queueUsage\x12'\n" +
	"\x0fdef_persistence\x18\x06 \x01(\x05R\x0edefPersistence\x12\x1f\n" +
	"\vinhibit_get\x18\a \x01(\x05R\n" +
	"inhibitGet\x12\x1f\n" +
	"\vinhibit_put\x18\b \x01(\x05R\n" +
	"inhibitPut\x12&\n" +
	"\x0fcurrent_q_depth\x18\t \x01(\x05R\rcurrentQDepth\x12\x1e\n" +
	"\vmax_q_depth\x18\n" +
	" \x01(\x05R\tmaxQDepth\x12(\n" +
	"\x10open_input_count\x18\v \x01(\x05R\x0eopenInputCount\x12*\n" +
	"\x11open_output_count\x18\f \x01(\x05R\x0fopenOutputCount\x12\x14\n" +
	"\x05error\x18\r \x01(\tR\x05error2\xb5\x02\n" +
	"\x0eMqGrpcServices\x12,\n" +
	"\x03Put\x12\x10.mqpb.PutRequest\x1a\x11.mqpb.PutResponse\"\x00\x12,\n" +
	"\x03Get\x12\x10.mqpb.GetRequest\x1a\x11.mqpb.GetResponse\"\x00\x12?\n" +
	"\vBrowseFirst\x12\x18.mqpb.BrowseFirstRequest\x1a\x14.mqpb.BrowseResponse\"\x00\x12=\n" +
	"\n" +
	"BrowseNext\x12\x17.mqpb.BrowseNextRequest\x1a\x14.mqpb.BrowseResponse\"\x00\x12G\n" +
	"\fInquireQueue\x12\x19.mqpb.InquireQueueRequest\x1a\x1a.mqpb.InquireQueueResponse\"\x00B\x0fZ\r./mq_grpc_apib\x06proto3"

var (
	file_mq_proto_rawDescOnce sync.Once
	file_mq_proto_rawDescData []byte
)

func file_mq_proto_rawDescGZIP() []byte {
	file_mq_proto_rawDescOnce.Do(func() {
		file_mq_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mq_proto_rawDesc), len(file_mq_proto_rawDesc)))
	})
	return file_mq_proto_rawDescData
}

var file_mq_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_mq_proto_goTypes = []any{
	(*PutRequest)(nil),           // 0: mqpb.PutRequest
	(*PutResponse)(nil),          // 1: mqpb.PutResponse
	(*GetRequest)(nil),           // 2: mqpb.GetRequest
	(*GetResponse)(nil),          // 3: mqpb.GetResponse
	(*BrowseFirstRequest)(nil),   // 4: mqpb.BrowseFirstRequest
	(*BrowseNextRequest)(nil),    // 5: mqpb.BrowseNextRequest
	(*BrowseResponse)(nil),       // 6: mqpb.BrowseResponse
	(*InquireQueueRequest)(nil),  // 7: mqpb.InquireQueueRequest
	(*InquireQueueResponse)(nil), // 8: mqpb.InquireQueueResponse
}
var file_mq_proto_depIdxs = []int32{
	0, // 0: mqpb.MqGrpcServices.Put:input_type -> mqpb.PutRequest
	2, // 1: mqpb.MqGrpcServices.Get:input_type -> mqpb.GetRequest
	4, // 2: mqpb.MqGrpcServices.BrowseFirst:input_type -> mqpb.BrowseFirstRequest
	5, // 3: mqpb.MqGrpcServices.BrowseNext:input_type -> mqpb.BrowseNextRequest
	7, // 4: mqpb.MqGrpcServices.InquireQueue:input_type -> mqpb.InquireQueueRequest
	1, // 5: mqpb.MqGrpcServices.Put:output_type -> mqpb.PutResponse
	3, // 6: mqpb.MqGrpcServices.Get:output_type -> mqpb.GetResponse
	6, // 7: mqpb.MqGrpcServices.BrowseFirst:output_type -> mqpb.BrowseResponse
	6, // 8: mqpb.MqGrpcServices.BrowseNext:output_type -> mqpb.BrowseResponse
	8, // 9: mqpb.MqGrpcServices.InquireQueue:output_type -> mqpb.InquireQueueResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_mq_proto_init() }
func file_mq_proto_init() {
	if File_mq_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mq_proto_rawDesc), len(file_mq_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mq_proto_goTypes,
		DependencyIndexes: file_mq_proto_depIdxs,
		MessageInfos:      file_mq_proto_msgTypes,
	}.Build()
	File_mq_proto = out.File
	file_mq_proto_goTypes = nil
	file_mq_proto_depIdxs = nil
}
