// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: mq.proto

package mq_grpc_api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	MqGrpcServices_Put_FullMethodName = "/mqpb.MqGrpcServices/Put"
	MqGrpcServices_Get_FullMethodName = "/mqpb.MqGrpcServices/Get"
)

// MqGrpcServicesClient is the client API for MqGrpcServices service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MqGrpcServicesClient interface {
	Put(ctx context.Context, in *PutRequest, opts ...grpc.CallOption) (*PutResponse, error)
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
}

type mqGrpcServicesClient struct {
	cc grpc.ClientConnInterface
}

func NewMqGrpcServicesClient(cc grpc.ClientConnInterface) MqGrpcServicesClient {
	return &mqGrpcServicesClient{cc}
}

func (c *mqGrpcServicesClient) Put(ctx context.Context, in *PutRequest, opts ...grpc.CallOption) (*PutResponse, error) {
	out := new(PutResponse)
	err := c.cc.Invoke(ctx, MqGrpcServices_Put_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mqGrpcServicesClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, MqGrpcServices_Get_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MqGrpcServicesServer is the server API for MqGrpcServices service.
// All implementations must embed UnimplementedMqGrpcServicesServer
// for forward compatibility
type MqGrpcServicesServer interface {
	Put(context.Context, *PutRequest) (*PutResponse, error)
	Get(context.Context, *GetRequest) (*GetResponse, error)
	mustEmbedUnimplementedMqGrpcServicesServer()
}

// UnimplementedMqGrpcServicesServer must be embedded to have forward compatible implementations.
type UnimplementedMqGrpcServicesServer struct {
}

func (UnimplementedMqGrpcServicesServer) Put(context.Context, *PutRequest) (*PutResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Put not implemented")
}
func (UnimplementedMqGrpcServicesServer) Get(context.Context, *GetRequest) (*GetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedMqGrpcServicesServer) mustEmbedUnimplementedMqGrpcServicesServer() {}

// UnsafeMqGrpcServicesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MqGrpcServicesServer will
// result in compilation errors.
type UnsafeMqGrpcServicesServer interface {
	mustEmbedUnimplementedMqGrpcServicesServer()
}

func RegisterMqGrpcServicesServer(s grpc.ServiceRegistrar, srv MqGrpcServicesServer) {
	s.RegisterService(&MqGrpcServices_ServiceDesc, srv)
}

func _MqGrpcServices_Put_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MqGrpcServicesServer).Put(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MqGrpcServices_Put_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MqGrpcServicesServer).Put(ctx, req.(*PutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MqGrpcServices_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MqGrpcServicesServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MqGrpcServices_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MqGrpcServicesServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MqGrpcServices_ServiceDesc is the grpc.ServiceDesc for MqGrpcServices service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MqGrpcServices_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mqpb.MqGrpcServices",
	HandlerType: (*MqGrpcServicesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Put",
			Handler:    _MqGrpcServices_Put_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _MqGrpcServices_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mq.proto",
}
