// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: mq.proto

package mq_grpc_api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MqGrpcServices_Put_FullMethodName         = "/mqpb.MqGrpcServices/Put"
	MqGrpcServices_Get_FullMethodName         = "/mqpb.MqGrpcServices/Get"
	MqGrpcServices_BrowseFirst_FullMethodName = "/mqpb.MqGrpcServices/BrowseFirst"
	MqGrpcServices_BrowseNext_FullMethodName  = "/mqpb.MqGrpcServices/BrowseNext"
)

// MqGrpcServicesClient is the client API for MqGrpcServices service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MqGrpcServicesClient interface {
	Put(ctx context.Context, in *PutRequest, opts ...grpc.CallOption) (*PutResponse, error)
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
	BrowseFirst(ctx context.Context, in *BrowseFirstRequest, opts ...grpc.CallOption) (*BrowseResponse, error)
	BrowseNext(ctx context.Context, in *BrowseNextRequest, opts ...grpc.CallOption) (*BrowseResponse, error)
}

type mqGrpcServicesClient struct {
	cc grpc.ClientConnInterface
}

func NewMqGrpcServicesClient(cc grpc.ClientConnInterface) MqGrpcServicesClient {
	return &mqGrpcServicesClient{cc}
}

func (c *mqGrpcServicesClient) Put(ctx context.Context, in *PutRequest, opts ...grpc.CallOption) (*PutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PutResponse)
	err := c.cc.Invoke(ctx, MqGrpcServices_Put_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mqGrpcServicesClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, MqGrpcServices_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mqGrpcServicesClient) BrowseFirst(ctx context.Context, in *BrowseFirstRequest, opts ...grpc.CallOption) (*BrowseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BrowseResponse)
	err := c.cc.Invoke(ctx, MqGrpcServices_BrowseFirst_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mqGrpcServicesClient) BrowseNext(ctx context.Context, in *BrowseNextRequest, opts ...grpc.CallOption) (*BrowseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BrowseResponse)
	err := c.cc.Invoke(ctx, MqGrpcServices_BrowseNext_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MqGrpcServicesServer is the server API for MqGrpcServices service.
// All implementations must embed UnimplementedMqGrpcServicesServer
// for forward compatibility.
type MqGrpcServicesServer interface {
	Put(context.Context, *PutRequest) (*PutResponse, error)
	Get(context.Context, *GetRequest) (*GetResponse, error)
	BrowseFirst(context.Context, *BrowseFirstRequest) (*BrowseResponse, error)
	BrowseNext(context.Context, *BrowseNextRequest) (*BrowseResponse, error)
	mustEmbedUnimplementedMqGrpcServicesServer()
}

// UnimplementedMqGrpcServicesServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMqGrpcServicesServer struct{}

func (UnimplementedMqGrpcServicesServer) Put(context.Context, *PutRequest) (*PutResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Put not implemented")
}
func (UnimplementedMqGrpcServicesServer) Get(context.Context, *GetRequest) (*GetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedMqGrpcServicesServer) BrowseFirst(context.Context, *BrowseFirstRequest) (*BrowseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BrowseFirst not implemented")
}
func (UnimplementedMqGrpcServicesServer) BrowseNext(context.Context, *BrowseNextRequest) (*BrowseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BrowseNext not implemented")
}
func (UnimplementedMqGrpcServicesServer) mustEmbedUnimplementedMqGrpcServicesServer() {}
func (UnimplementedMqGrpcServicesServer) testEmbeddedByValue()                        {}

// UnsafeMqGrpcServicesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MqGrpcServicesServer will
// result in compilation errors.
type UnsafeMqGrpcServicesServer interface {
	mustEmbedUnimplementedMqGrpcServicesServer()
}

func RegisterMqGrpcServicesServer(s grpc.ServiceRegistrar, srv MqGrpcServicesServer) {
	// If the following call panics, it indicates UnimplementedMqGrpcServicesServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MqGrpcServices_ServiceDesc, srv)
}

func _MqGrpcServices_Put_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MqGrpcServicesServer).Put(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MqGrpcServices_Put_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MqGrpcServicesServer).Put(ctx, req.(*PutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MqGrpcServices_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MqGrpcServicesServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MqGrpcServices_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MqGrpcServicesServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MqGrpcServices_BrowseFirst_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BrowseFirstRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MqGrpcServicesServer).BrowseFirst(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MqGrpcServices_BrowseFirst_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MqGrpcServicesServer).BrowseFirst(ctx, req.(*BrowseFirstRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MqGrpcServices_BrowseNext_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BrowseNextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MqGrpcServicesServer).BrowseNext(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MqGrpcServices_BrowseNext_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MqGrpcServicesServer).BrowseNext(ctx, req.(*BrowseNextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MqGrpcServices_ServiceDesc is the grpc.ServiceDesc for MqGrpcServices service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MqGrpcServices_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mqpb.MqGrpcServices",
	HandlerType: (*MqGrpcServicesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Put",
			Handler:    _MqGrpcServices_Put_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _MqGrpcServices_Get_Handler,
		},
		{
			MethodName: "BrowseFirst",
			Handler:    _MqGrpcServices_BrowseFirst_Handler,
		},
		{
			MethodName: "BrowseNext",
			Handler:    _MqGrpcServices_BrowseNext_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mq.proto",
}
