#FROM golang:1.25-bookworm AS builder
#
#RUN apt-get update && apt-get install -y gcc ca-certificates && rm -rf /var/lib/apt/lists/*
#
#COPY mq-client/ /opt/mqm/
#
#ENV CGO_ENABLED=1
#ENV GO111MODULE=on
#ENV CC=gcc
#ENV CGO_CFLAGS="-I/opt/mqm/tools/c/include -D_REENTRANT"
#ENV CGO_LDFLAGS="-L/opt/mqm/tools/lib64 -lmqm"
#
#WORKDIR /app
#
#COPY go.mod go.sum ./
#RUN go mod download
#
#COPY . .
#
#RUN go clean -cache
#RUN mkdir -p /out
##RUN go build -v -o /out/mq-gateway ./
## Build with debug flags
#RUN CGO_ENABLED=0 go build -gcflags="all=-N -l" -o /out/mq-gateway ./
FROM golang:1.25 AS build

WORKDIR /src

# Copy module files if present (go.sum is optional)
COPY go.mod ./
# Don't copy go.sum separately; just copy everything next
COPY . .

RUN ls -l
RUN pwd

# Download deps (works even if go.sum doesn't exist)
RUN go mod download

# Build with debug flags
RUN CGO_ENABLED=0 go build -gcflags="all=-N -l" -o /out/mq-gateway ./



# Runtime stage (Debian-based is easiest for dlv)
FROM debian:bookworm-slim
WORKDIR /app

# Install certs (optional but common)
RUN apt-get update && apt-get install -y --no-install-recommends ca-certificates && rm -rf /var/lib/apt/lists/*

# Copy binary
COPY --from=build /out/app /app/app

# Install Delve (download a released dlv binary via apt is not always available)
# Easiest: copy dlv from a golang stage that installs it.
# We'll do it via an extra stage.


FROM golang:1.25 AS dlv

RUN go install github.com/go-delve/delve/cmd/dlv@latest

FROM debian:bookworm-slim

RUN apt-get update && apt-get install -y ca-certificates libstdc++6 libgcc-s1 && rm -rf /var/lib/apt/lists/*


COPY --from=builder /opt/mqm /opt/mqm

# Make /opt/mqm/tools/lib64 part of the dynamic linker search path
RUN echo "/opt/mqm/tools/lib64" > /etc/ld.so.conf.d/mqm.conf && ldconfig

# Optional (kept for clarity; ldconfig is the important part)
ENV LD_LIBRARY_PATH=/opt/mqm/tools/lib64

COPY --from=builder /out/mq-gateway /usr/local/bin/mq-gateway
COPY --from=dlv /go/bin/dlv /usr/local/bin/dlv

EXPOSE 8080 9090 2345
#CMD ["mq-gateway"]
CMD ["dlv","exec", "/app/app", "--headless", "--listen=:2345","--api-version=2", "--accept-multiclient","--continue","--log"]



#FROM golang:1.25-bookworm AS builder
#RUN apt-get update && apt-get install -y gcc ca-certificates && rm -rf /var/lib/apt/lists/*
#WORKDIR /app
#COPY go.mod go.sum ./
#RUN go mod download
#COPY . .
#RUN go build -v -o /out/mq-gateway ./cmd/mq-gateway
#
#FROM icr.io/ibm-messaging/mq:9.3.2.0-r2
#COPY --from=builder /out/mq-gateway /usr/local/bin/mq-gateway
#EXPOSE 8080 9090
#CMD ["mq-gateway"]
