Build_docker-compose.debug.mq-sdk.local:
	docker compose -f docker-compose.debug.mq-sdk.local.yml build --no-cache --progress=plain

Run_docker-compose.debug.mq-sdk.local:
	docker compose -f docker-compose.debug.mq-sdk.local.yml up

Exit_docker-compose.debug.mq-sdk.local:
	docker compose -f docker-compose.debug.mq-sdk.local.yml down

Recreate_docker-compose.debug.mq-sdk.local:
	docker compose -f docker-compose.debug.mq-sdk.local.yml up --force-recreate

Show_Logs_docker-compose.debug.mq-sdk.local:
	docker compose -f docker-compose.debug.mq-sdk.local.yml logs -f
